{% set version = "0.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-splines2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/splines2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/splines2/splines2_{{ version }}.tar.gz
  sha256: 0be5949301d90d1c983878115097d162e866ed5aafb4ba88b5f86291d62972f3

build:
  merge_build_host: true  # [win]
  skip: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - libblas
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-rcpparmadillo

test:
  commands:
    - $R -e "library('splines2')"           # [not win]
    - "\"%R%\" -e \"library('splines2')\""  # [win]

about:
  home: https://github.com/wenjie2wang/splines2
  license: GPL-3.0-or-later
  summary: Constructs B-splines and its integral, M-splines and its integral (I-splines), convex splines (C-splines), generalized Bernstein polynomials, and their derivatives. It also contains a C++ head-only library integrated with Rcpp. See De Boor (1978) <doi:10.1002/zamm.19800600129>, Ramsay (1988) <doi:10.1214/ss/1177012761>,
    and Meyer (2008) <doi:10.1214/08-AOAS167> for more information about the spline basis.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
